include:
- function/*
kind: ArchiveUploadSpec
name: function-yh73

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: function-854b4028-5e7b-4fcf-bb40-a75fd498d19e
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: nodejs
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://function-yh73
status:
  buildstatus: pending
  lastUpdateTimestamp: "2021-07-05T08:16:51Z"
